language: c
dist: xenial
sudo: required
addons:
  apt:
    packages:
      - qemu-system-x86
      - libseccomp-dev
env:
  global:
    - SURF_BUILD_TYPE=basic
    - SURF_SUDO=sudo
    - SURF_RUN_TESTS=yes
before_script:
  - git config user.email travis@example.com
  - git config user.name "Travis CI"
script: ./build.sh
jobs:
  include:
    - name: Build and test spt, virtio
      os: linux
      arch: amd64
    - name: Build and test spt
      os: linux
      arch: arm64
    - name: Build and test spt
      env: CC=gcc-7
      os: linux
      arch: ppc64le
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -y update
        - sudo apt-get -y install gcc-7
